print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')

print ('Here is another line.')
#print("So if I add '#' before my code, this line won't display on the screen, which is a comment symbol like that in R)
